# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bd0fc636d132bd78ab76c8d4c5b86d13c730d8001df1c759e7afca38d6c9ff077685e36a2f36d7b7b6292998662b3f16ac2589ebba3a7468f4b06b3c8f73b49

test:
  secret_key_base: cfddacf543c90753a2aaf85d49f75ab5bd7aceafbeec8b1042794ee3df2b190f425ae9d4bd80f7c0b795af04f5fe32778c2118b1fc4983f2a1b2d8a6a284a72e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
